server:
  port: 8080
spring:
  application:
    name: "tourFrance"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://prueba1:prueba1@cluster0.evwtm.mongodb.net/?retryWrites=true&w=majority"
      database: "tourFrance"
      auto-index-creation: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
